### PR TITLE
Added short cli options

### PR DESCRIPTION
**Pull request by emanuelbuholzer**
Added short cli options for version and help

### CODE REVIEW

**Comment by emanuelbuholzer** [comment]
This is just version and help. I'll commit a pr with the short cli options for commands later this day.

**Comment by emanuelbuholzer** [comment]
Like this?

**Comment by dfrownfelter** [comment]
Thanks! I'm going to merge this request and close the other one because it has the removal of markdown as well

**Comment by emanuelbuholzer** [comment]
Ah I see, oopsy

**Pull request merged**
