### PR TITLE
#2 - Adding customizable logger.

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**

### CODE REVIEW

**Comment by dvidsilva** [comment]
Hi, thanks for the contribution. Take a look at the `.jscsrc` file. Mostly, we're using 4 spaces for indentation and trailing commas in object definitions. 

You can take a look at the fix here. 

https://github.com/gloriajs/gloria/tree/IAmAnubhavSaini-logger 

If you're cool with merging that I will include the PR

**Comment by IAmAnubhavSaini** [comment]
Who consumes `.jscsrc` file?
Is it okay if I add an `.editorconfig` file?

**Comment by dvidsilva** [comment]
For now we're trying to keep editorconfigs out of the repo.

.jscrc is consumed by http://jscs.info/overview 

You can run the command line tool, but that's a bit harder. Personally I use https://code.visualstudio.com/ visual studio code, is really easy to get that going. But there has to be plugins for any editor you have. 

Let me know which one you use and I can try and find more info.

**Comment by dvidsilva** [comment]
We use the airbnb style guide. https://github.com/airbnb/javascript

**Comment by IAmAnubhavSaini** [comment]
Is something missing from this PR

**Comment by dvidsilva** [comment]
Nothing, sorry, merging now.

**Comment by IAmAnubhavSaini** [comment]
@dvidsilva I think you closed it instead of merging it.

**Comment by dvidsilva** [comment]
Thanks, my bad :p still learning this.

**Comment by dvidsilva** [comment]
My bad. merged!

**Pull request merged**
